server:
    port: 9001
name:
    '{cipher}AQCKQQ8M3mKQRPOJKmlq/mrSYg12JKIhR/XXsftGkS8yJlH6Ft/PWymWKVdr1ftrh5hEqRkqXMF8tQb5l36/lYJdKhGFB7zvAYD1P06gf3OsS7KiQ9nWQ64kslklUDVo/NB3zoLbUG5QegduA1SZ3udRQ73LH3C29R3pKq9GLa34o2dTYU2PP4QWpW2C+8j3OWoHeN82QX4xHEmhkM2f1aJeZSqICeoxLpgipf85mkyoQ2e99AyP3BsXuJMvNzXetPS4A41wOPMpEp6CYJ5raW/dxitFWb9EHU9wnv+m3451JUc5NJRhh8G5/CtlzuikdtlC3U7Q+gHBU8bewA7HzJWisX2w+SaSKYXoWPQx6d0z2dwO3y5Y7xJffw4j7A8d8Kw='
    
#zuul:
    #routes:
        #service-a:
         #   path: /service-ssdev/**
          #  serviceId: hello.service-a