server:
    port: 9001
name:
    '{cipher}AQA5eCOjmU6YGKxgTgCyYTXoGl9Wi7feqjDHMNb5FH/AHWfNEZsNjFzU5yF8m2ZvRH4bZZPfgD0056KvcEvZDeS1PY+O//2Q2DRE/kiwiatse6o7PV+qnjarBdybH5dIJauDf75MJ7q8cgrsLhwhvbsKEucNcVTBQHjPn7ObgFQLfA6vpbMnjhvqKhyYL7DD/zEXOMO7oa5ehAL4r9s/IarvwKoPQb1Sd1HOkOGX+8CBaYCgtKyTi2RQUtBeMM3cs7OkF2txd4PXBucSyy1o37mA/pWah34y9rVfz/YsLJaIcSjI+fwzh1GClPTs/5ZyxE68xgoB60Iz67gwZrk9ezAjzC37SdUGtyXUYebdC2RdojSczQ2i4/FqlG2NRmyldmk='
#zuul:
    #routes:
        #service-a:
         #   path: /service-ssdev/**
          #  serviceId: hello.service-a