server:
    port: 9001
name:
    '{cipher}AQBgcin8kNeyc+1UpQ4xOfUXgTjfvT7eZ2G1yxphThtHIOhnyRm3XeUCbejoi70x0BW+CYpvoqNjKzFPCr5b834BdBp5G+Tif2o1z++c6SKwvaAovIDQZjPw8Ze+eIDweykfTHODy0t7Sd19cexe3IkVxfgFtsTsAbkfu5pax2Is73b1pbTgUIKEMkSCo6PRHe3DfDWuXic3zsb+d5auUdNOZn4wpEGZlb2oPm0g1Rscb5cWS2MY0dsWNB9YTP4DnHTQBV6IZS64y3Gs+wev/ZhRS7LjHuFBazauwfkpb7pJxjS7t/4e25jEw82EoiF9i9+jaFDcBDDpR0wnviAQXIxBOGgaMQImAqVdsTPNHbW6+SAooZ3r+IECauvmIwqPS1I='
#zuul:
    #routes:
        #service-a:
         #   path: /service-ssdev/**
          #  serviceId: hello.service-a