server:
    port: 9002
name:
    '{cipher}AQCQp2uLeYsnDeo0MzjlmuaN7Kfza/u8YokzJc81LL2Qzx+Evt9ESjQzUCQ820ilXZD0NJiVpnZL2VoWLk4ZD04NqHwbLWcAHmU2QFg3neygfUv3VL9hbdKQ+uJWD6FwdXv4w2zwXBgQZ+U3f7s9Vf1/hzkmVTSeeneKImLiQdUR0KxbkhD2/KVGbt/8XlgxZ/t29X3eSLz6E8fJ0dAsWSbCCMX9NDx68gGBHuFd4/eEu4S4Yi1wg5AuQr6nrcXjzPjSgiSVCAImmRpaBv5wfVKN8njRN4t81poA8XhsukCWR1/vPYnEx8u54AQxD4RVerXepz8LIvWGKsgIBaI+pFUsBJVnmUfNmWithVGXVO1BPxw2o7/JG/eBpQZExmH02qw='
    
#zuul:
    #routes:
        #service-a:
         #   path: /service-ssdev/**
          #  serviceId: hello.service-a