server:
    port: 9999
name:
    '{cipher}AQAUOJ5Gna6UGfxd/r5s/xPVNY0WUCrlXwKzLslpWnFMkRRVLVIPTagqjs/bdKmK21/pkwRwVpsvQa+LafOsY7T0oEVDK/TenzyAb3zbRFeyBH9BinamZHAXPWBB9OsACVoEHSfFGvzjlW6PTO4BP6qdsrTp4oaYN8ZUsotr3SCVfhAIUfXUI1g7YQzwXK42KfZ+Oy14oZvwOxuSPgkm42SMUB5JR1nWu+1x/b1JkPHZN+R1uw3GETqq+r6MHIL1XuBwRo/caYiZdGUVobipAVM8psZbnWwXpxfPe33xqdwBiGScmd5XUUhW0jSmgxgVESUeuRlcbGSuNMT+A5hi1U/0+lMojEP4vEfD8UveLAYU7wHA91T4F7jiBmHAB6FTrDM='
#zuul:
    #routes:
        #service-a:
         #   path: /service-ssdev/**
          #  serviceId: hello.service-a