server:
    port: 9999
name:
    '{cipher}AQAUrmPzD+6TQdtrN49fYb5vLesi1JJSX2RsoS4AVJa7ezEsLVmbupJHUMfP37i/ka1Un3SozRDhquULySQ5r0Wm08/ihqhvq+Kuaxf7rP9+GzjD/yLkO/YPHjGiE8o0SQZl1AufRAymOzZFFupyQ71UAaD4A+vGkDTxAcqFChgqtznb1p5VWR9fi1IQR5/aazAloOidNpQdRAkv2DlQrPSiEttzjqDi9XHgkJDLs8UXsiTDB6hJeeSyZT6D8xVW9gj+cnqZ6QEZcuNHaVNTQVlAYiMKCR/kZ//14tB/75TBuhs+WMT7PpgozC9i2zW7mXKYHpE8lRIpqn/elzB3zWkBAFdoPJ/zhBqLYK/8fPQhrSM3hhyWEXdVMFBqLJkgZ0c='
#zuul:
    #routes:
        #service-a:
         #   path: /service-ssdev/**
          #  serviceId: hello.service-a