server:
    port: 9001
name:
    '{cipher}AQCYQUorbimqWpTEo8/TqWZvCwCuyHr61p8CdUHGVZVp51SY4rNUC/DoFGMellAcD3ahAd4ca4jQkzFd+Bb597CkvOE7/sHhQJw2kFPEs6QSZv/TPI/GVaD+hVDIWFU78k8o1ZCfXfoLWV3JiVjz9CsfZS2yF5Xu/hyoA659ODIHmceajui9QbNlIf4Y7kZTWQE9h+LWfUYMW5s/dJLysLqe6WfT8Hsce6bxwQabKgTZsnalCWXDdq3aeByyGw9k4H3Lu6BjWOsk2kcVNOX+sYvvW5L/AH4qUqydcBP4+ZnWbMhrrJi2d/SlifUozlkDjxdJp3cJTM+/73oqvO6frKXG06XVGgiAG4Gqu2J4s8SvLsQ1WFho3/PVqQpGEhbgwXs='
#zuul:
    #routes:
        #service-a:
         #   path: /service-ssdev/**
          #  serviceId: hello.service-a