server:
    port: 9002
name:
    '{cipher}AQBQujiCQE5zxl2iVr8jmuvfLXWuX/p/pk87bUBvcBEc7P3ThMM0BLU9a6/LwVjzjZ31/iQuw927bSw6C6Fv3p0JZRcv4r3iKy6l4fKu33Ts6/K4SbcyTPgl7IcvJx14y5s/pVVjjFk6U9tW+lx+3GXdcQOvORb3Rxy4FdgFh+E5ApLHYB6E1AhHSUMsFaIi2elnBDJeG0aTduEeoxLW/04QMx1+t+Fr3jOWoMaFYHRX9V9cDMwyr5NtGnCVo+GkuFWTEBfcVIh7msrgcZaM3gq+fHzuu0K48Qlw+EnULQCIt2pjcB0o/0yOfBt7rmvQcreVRXBi8qxwpsaAOerZ6SpVjf8ZwDJnNydNlgXCSQGoRlK71KmWnF0wV1saBs62KjQ='
    
#zuul:
    #routes:
        #service-a:
         #   path: /service-ssdev/**
          #  serviceId: hello.service-a