server:
    port: 9001
name:
    '{cipher}AQB2HVCHxM/7oujLaKKILLVtGC2YdA6mAMeGLFf5Flx60Wjc/aahq5H4z2/JJhvsBzaTnDvzjh1BtQq8xH5ciGuArGzGthMG/CK2Mea/WU2FerAGKMX9rPrUh6ziB3Nfv5lkpmY+lx+kBL2XAlJ0jXIr6Yp3VAAS5HrXidFsqmL5GZV4ZvPz0+TYBvMnwIGgbZ+FaA1OMhZy6ophbrstFIhHmHHp/gPqS2RDYuTVOMALHDwDMzc1H6s0dWO5tb1TQSL6pnAW8e56Y/8hnTziANTtB+4GuTPMlW8cc0/Ev6A44lPQPz92aNjQ9EsvmnFp7VAjovTtlTp4w+XwJ3z4pxLlj8S3z7MP1LM9loefL75Jx1dxPoKmZmSVMim9L1+NU9A='
    
#zuul:
    #routes:
        #service-a:
         #   path: /service-ssdev/**
          #  serviceId: hello.service-a