server:
    port: 9001
name:
    '{cipher}AQAufKwCmV/Vdv/U0oWAdOEqRRufVS6FP7O5W83o3w50fWjM5FD0Ad9KN202JkuVis1Sfd8u0NLNg1ww4pv3KhoOLMScNRkQU9m4pI4ccmy3wXxexPQecs1BhZ2ld1ImC8vnTim35sIpKTEWJn7SllwNDAPJmqRR/5kk6Y/ZpCcWI74rL/hLFkDGzFjNC1TKETkl+YO/FNGW4G7Ni4Jq8W0se+ic/Cu2nyhPNWuirGUJOEdZdTDz7+a/7w+TOfxR63T1z3nG/nMeNTpqTcvXAm+Wop81SXUD7qM3fDWybahjFRAyhohBNNGjEHADw7ctnnJID0l0IJThAiCFQAmMQiVXXIWIkZQP2P/jdgLafjoXfmEWXW8X4xaJb2c1gC7FdNM='
#zuul:
    #routes:
        #service-a:
         #   path: /service-ssdev/**
          #  serviceId: hello.service-a