server:
    port: 9002
name:
    '{cipher}AQCWoMWqqkJM/pyxhD9O268wYzUoKIGCdfa5O6CtFF+s9tFeuTA50RioBMQWKJ3aspjx8EZ00bR8vJw5OCOS765PftVIqWKKf2d626XSDx2+7/EePavuU9FwpTuXEF46llIOeGfgMpGYgBwI2zNGRJHiwjY0y5m/kU8YZy4+yVoDA8eqzhpqX7MmGhSWr31vXJzt6PJyeB31/vq54doWI+PhIVBxX6uHbfNZZhD8qH7BPxca3dm9x9VEcgvxRBEHNCRmiG2qXc6M27CUyBdfwtvqDFnI/vw+BmIVKfBL/3Va4Kbjz4lbpKWlnG1d2lFLiD/zxghLQn3kWbIFk7esvJF28F/wd2TW0Yi1coK97g7sAsrjxYuDdrT2nxv5EP7X9EQ='
    
#zuul:
    #routes:
        #service-a:
         #   path: /service-ssdev/**
          #  serviceId: hello.service-a